{% set version = "1.0.3" %}
{% set commit = "58fa4d15fff10f26c490518bc0da2b69732e22ee" %}

package:
  name: mpc
  version: {{ version }}

source:
  fn: mpc-{{ version }}.tar.gz                                              # [unix]
  url: http://www.multiprecision.org/mpc/download/mpc-{{ version }}.tar.gz  # [unix]
  sha1: b8be66396c726fdc36ebb0f692ed8a8cca3bcc66                            # [unix]
  fn: {{ commit }}.zip                                                      # [win]
  url: https://github.com/BrianGladman/mpc/archive/{{ commit }}.zip         # [win]
  md5: a3ccbbb17770110427a983638824f31b                                     # [win]

build:
  number: 3
  skip: true          # [win and not py35]
  features:
    - vc14            # [win and py35]

requirements:
  build:
    - toolchain
    - python          # [win]
    - m4              # [unix]
    - libtool         # [unix]
    - gmp             # [unix]
    - mpir            # [win]
    - mpfr
  run:
    - gmp             # [unix]
    - mpir            # [win]
    - vc 14           # [win]
    - mpfr

test:
  commands:
    - if not exist %LIBRARY_INC%\\mpc.h exit 1                  # [win]
    - if not exist %LIBRARY_LIB%\\mpc.lib exit 1                # [win]
    - if not exist %LIBRARY_BIN%\\mpc.dll exit 1                # [win]
    - if not exist %LIBRARY_LIB%\\mpc_static.lib exit 1         # [win]
    - test -f ${PREFIX}/include/mpc.h                           # [unix]
    - test -f ${PREFIX}/lib/libmpc.a                            # [unix]
    - test -f ${PREFIX}/lib/libmpc.dylib                        # [osx]
    - test -f ${PREFIX}/lib/libmpc.so                           # [linux]

about:
  home: http://www.multiprecision.org/
  license: LGPL 3
  license_file: COPYING.LESSER
  summary: A C library for the arithmetic of complex numbers with arbitrarily high precision.

extra:
  recipe-maintainers:
    - isuruf
    - jakirkham
